-- This file is autogenerated (edit palettes/mariana.ini to change)
return {
  bg0     = "#1e2730",
  bg1     = "#242f39",
  bg2     = "#2b3642",
  bg3     = "#33404e",
  bg4     = "#3e4d5c",

  fg0     = "#d8dee9",
  fg1     = "#b8c0cc",
  fg2     = "#8895a0",
  fg3     = "#5c6773",

  red     = "#ec5f67",
  orange  = "#f99157",
  yellow  = "#fac863",
  green   = "#99c794",
  cyan    = "#5fb3b3",
  blue    = "#6699cc",
  purple  = "#c594c5",
  pink    = "#ec5f67",

  err     = "#ec5f67",
  warn    = "#fac863",
  info    = "#6699cc",
  hint    = "#99c794",
  added   = "#99c794",
  changed = "#f99157",
  removed = "#ec5f67",

  none    = "NONE",
}
