-- This file is autogenerated (edit palettes/mokka.ini to change)
return {
  bg0     = "#232323",
  bg1     = "#2b2b2b",
  bg2     = "#323232",
  bg3     = "#3c3c3c",
  bg4     = "#505050",

  fg0     = "#eeeee8",
  fg1     = "#c8c6c0",
  fg2     = "#929088",
  fg3     = "#626058",

  red     = "#f92672",
  orange  = "#fd971f",
  yellow  = "#e6db74",
  green   = "#a6e22e",
  cyan    = "#66d9ef",
  blue    = "#66d9ef",
  purple  = "#ae81ff",
  pink    = "#f92672",

  err     = "#f92672",
  warn    = "#e6db74",
  info    = "#66d9ef",
  hint    = "#a6e22e",
  added   = "#a6e22e",
  changed = "#fd971f",
  removed = "#f92672",

  none    = "NONE",
}
