-- This file is autogenerated (edit palettes/mokka.ini to change)
return {
  bg0     = "#1e1c1a",
  bg1     = "#252220",
  bg2     = "#2d2a27",
  bg3     = "#38342f",
  bg4     = "#4f493f",

  fg0     = "#f8f8f2",
  fg1     = "#d8d4c8",
  fg2     = "#9e998a",
  fg3     = "#6b6557",

  red     = "#f92672",
  orange  = "#fd971f",
  yellow  = "#e6db74",
  green   = "#a6e22e",
  cyan    = "#66d9ef",
  blue    = "#66d9ef",
  purple  = "#ae81ff",
  pink    = "#f92672",

  err     = "#f92672",
  warn    = "#e6db74",
  info    = "#66d9ef",
  hint    = "#a6e22e",
  added   = "#a6e22e",
  changed = "#fd971f",
  removed = "#f92672",

  none    = "NONE",
}
