-- This file is autogenerated (edit palettes/umbra.ini to change)
return {
  bg0     = "#13111a",
  bg1     = "#1a1825",
  bg2     = "#21202e",
  bg3     = "#2c2a3d",
  bg4     = "#413e58",

  fg0     = "#e8e4d9",
  fg1     = "#c8c3b8",
  fg2     = "#8a8478",
  fg3     = "#57524a",

  red     = "#ff7b8b",
  orange  = "#ffb86c",
  yellow  = "#e5c890",
  green   = "#a9dc76",
  cyan    = "#78dce8",
  blue    = "#82aaff",
  purple  = "#c099ff",
  pink    = "#fc9867",

  err     = "#ff7b8b",
  warn    = "#e5c890",
  info    = "#82aaff",
  hint    = "#a9dc76",
  added   = "#a9dc76",
  changed = "#ffb86c",
  removed = "#ff7b8b",

  none    = "NONE",
}
