# scripts/generate.py

# This script must be ran on any change to the palette or template files.
import re
import configparser
import os

def generate_variant(variant_name, ini_path, template):
    # String to keep track of successful generations
    successful_generations = ""

    # Fill palette table
    config = configparser.ConfigParser()
    config.read(ini_path)

    palette = dict(config["palette"])

    generated = re.sub(r"\{\{(.+?)\}\}", lambda m: palette[m.group(1)], template)
    generated = f"-- This file is autogenerated (edit palettes/{variant_name}.ini to change)\n" + generated
    out_path = f"lua/mokka/palettes/{variant_name}.lua"
    with open(out_path, "w") as f:
        f.write(generated)
    successful_generations += f" - {out_path}\n"

    # Fill in terminal templates
    os.makedirs("extras", exist_ok=True)
    for filename in os.listdir("lua/mokka/extras"):
        filepath = os.path.join("lua/mokka/extras", filename)
        with open(filepath) as f:
            content = f.read()
        content_generated = re.sub(r"\{\{(.+?)\}\}", lambda m: palette[m.group(1)], content)

        write_path = os.path.join("extras", f"{variant_name}-{filename}")
        with open(write_path, "w") as f:
            f.write(content_generated)

        successful_generations += f" - {write_path}\n"

    os.makedirs("colors", exist_ok=True)
    if variant_name != "mokka":
        colors_content = f'vim.opt.background = "dark"\nrequire("mokka").setup({{ variant = "{variant_name}" }})\n'
    else:
        colors_content = f'vim.opt.background = "dark"\nrequire("mokka").load()\n'
    out_dir = "colors/mokka.lua" if variant_name == "mokka" else f"colors/mokka-{variant_name}.lua"
    with open(out_dir, "w") as f:
        f.write(colors_content)
    successful_generations += f" - {out_dir}\n"

    print(f"Successfully generated variant ({variant_name}):\n{successful_generations}\n")


def main():
    with open("lua/mokka/palette_template.lua", "r") as f:
        template = f.read()

    palettes_dir = "lua/mokka/palettes"
    os.makedirs(palettes_dir, exist_ok=True)

    for filename in os.listdir(palettes_dir):
        if filename.endswith(".ini"):
            variant_name = filename[:-4]
            ini_path = os.path.join(palettes_dir, filename)
            generate_variant(variant_name, ini_path, template)

if __name__ == "__main__":
    main()
