# Mokka — kitty terminal theme
# https://sw.kovidgoyal.net/kitty/conf/#color-scheme

background              #1e2730
foreground              #b8c0cc
selection_background    #33404e
selection_foreground    #d8dee9
cursor                  #b8c0cc
cursor_text_color       #1e2730
url_color               #6699cc

# Tabs
active_tab_background   #1e2730
active_tab_foreground   #d8dee9
inactive_tab_background #2b3642
inactive_tab_foreground #5c6773
tab_bar_background      #242f39

# Marks
mark1_background        #33404e
mark1_foreground        #d8dee9
mark2_background        #c594c5
mark2_foreground        #1e2730
mark3_background        #5fb3b3
mark3_foreground        #1e2730

# Black
color0  #1e2730
color8  #3e4d5c

# Red
color1  #ec5f67
color9  #ec5f67

# Green
color2  #99c794
color10 #99c794

# Yellow
color3  #fac863
color11 #fac863

# Blue
color4  #6699cc
color12 #6699cc

# Magenta / Purple
color5  #c594c5
color13 #ec5f67

# Cyan
color6  #5fb3b3
color14 #5fb3b3

# White
color7  #b8c0cc
color15 #d8dee9
