# Mokka — kitty terminal theme
# https://sw.kovidgoyal.net/kitty/conf/#color-scheme

background              #232323
foreground              #c8c6c0
selection_background    #3c3c3c
selection_foreground    #eeeee8
cursor                  #c8c6c0
cursor_text_color       #232323
url_color               #66d9ef

# Tabs
active_tab_background   #232323
active_tab_foreground   #eeeee8
inactive_tab_background #323232
inactive_tab_foreground #626058
tab_bar_background      #2b2b2b

# Marks
mark1_background        #3c3c3c
mark1_foreground        #eeeee8
mark2_background        #ae81ff
mark2_foreground        #232323
mark3_background        #66d9ef
mark3_foreground        #232323

# Black
color0  #232323
color8  #505050

# Red
color1  #f92672
color9  #f92672

# Green
color2  #a6e22e
color10 #a6e22e

# Yellow
color3  #e6db74
color11 #e6db74

# Blue
color4  #66d9ef
color12 #66d9ef

# Magenta / Purple
color5  #ae81ff
color13 #f92672

# Cyan
color6  #66d9ef
color14 #66d9ef

# White
color7  #c8c6c0
color15 #eeeee8
