# Mokka — kitty terminal theme
# https://sw.kovidgoyal.net/kitty/conf/#color-scheme

background              #13111a
foreground              #c8c3b8
selection_background    #2c2a3d
selection_foreground    #e8e4d9
cursor                  #c8c3b8
cursor_text_color       #13111a
url_color               #82aaff

# Tabs
active_tab_background   #13111a
active_tab_foreground   #e8e4d9
inactive_tab_background #21202e
inactive_tab_foreground #57524a
tab_bar_background      #1a1825

# Marks
mark1_background        #2c2a3d
mark1_foreground        #e8e4d9
mark2_background        #c099ff
mark2_foreground        #13111a
mark3_background        #78dce8
mark3_foreground        #13111a

# Black
color0  #13111a
color8  #413e58

# Red
color1  #ff7b8b
color9  #ff7b8b

# Green
color2  #a9dc76
color10 #a9dc76

# Yellow
color3  #e5c890
color11 #e5c890

# Blue
color4  #82aaff
color12 #82aaff

# Magenta / Purple
color5  #c099ff
color13 #fc9867

# Cyan
color6  #78dce8
color14 #78dce8

# White
color7  #c8c3b8
color15 #e8e4d9
